### ISSUE TITLE
有svg格式吗

### ISSUE THREAD

**Issue by Gloria-wgs** [itorr/ISO3166-1_icons#1]
国家的图片有有svg格式吗，国家对应的币种有吗

**Comment by itorr** [comment]
国家对应币种可以参考 https://zh.wikipedia.org/wiki/%E6%B5%81%E9%80%9A%E8%B2%A8%E5%B9%A3%E5%88%97%E8%A1%A8



svg 的话 也加上了 https://github.com/itorr/ISO3166-1_icons/commit/09a787c589f1a943bd68380aaf908845991091f6
